version: "3.9"

services:
  app:
    image: auth
    build:
      context: ./backend/auth/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/fastapi_db

  db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: